[package]
name = "aegis-scan"
description = "Motor de deteccion profunda de AegisCore: YARA sobre ficheros y memoria de procesos"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
thiserror = "2"
libc = "0.2"
arc-swap = "1"
yara-x = "0.8"
